[package]
name = "enum_access"
version = "0.1.0"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.14"
synstructure = "0.9"
